platform :ios, '7.0'
pod 'Reachability',  '~> 3.0.0'
pod 'JSONKit', :podspec => 'https://gist.github.com/jhonyf/7002734/raw/08fd7b28676b97af251b5dd5b375394eedc454f9/gistfile1.rb'
pod 'AFNetworking', '1.3.3'